# Generated by Django 5.2.16 on 2026-07-24 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='files.file'),
        ),
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='client.branch'),
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='files.file'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='branches',
            field=models.ManyToManyField(related_name='doctors', to='client.branch'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='files.file'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='client.doctor'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='client.branch'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='client.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='client.patient'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='client.booking'),
        ),
        migrations.AddField(
            model_name='service',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='client.department'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='files.file'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(related_name='doctors', to='client.service'),
        ),
        migrations.AddField(
            model_name='branch',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='branches', to='client.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='client.service'),
        ),
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.UniqueConstraint(fields=('doctor', 'branch', 'weekday', 'start_time'), name='unique_doctor_branch_slot'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('department', 'slug'), name='unique_service_slug_per_department'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['doctor', 'date'], name='client_book_doctor__2afe3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_payment', 'confirmed'])), fields=('doctor', 'date', 'start_time'), name='unique_active_slot'),
        ),
    ]
