# Generated by Django 5.2.16 on 2026-07-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_gallery_image_url_patient_address_and_more'),
        ('client', '0004_remove_gallery_image_url_patient_image_and_more'),
    ]

    operations = [
    ]
