# Generated by Django on 2026-07-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_merge_20260728_2003'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_primary_images', to='files.file'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_videos', to='files.file'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
