# Generated by Django 5.2.16 on 2026-08-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_gallery_media_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
